/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GoldenRouteImport } from './routes/golden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MisRouteImport } from './routes/mis'
import { Route as OverridesRouteImport } from './routes/overrides'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as RunRouteImport } from './routes/run'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldenRoute = GoldenRouteImport.update({
  id: '/golden',
  path: '/golden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MisRoute = MisRouteImport.update({
  id: '/mis',
  path: '/mis',
  getParentRoute: () => rootRouteImport,
} as any)
const OverridesRoute = OverridesRouteImport.update({
  id: '/overrides',
  path: '/overrides',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/desk': typeof DeskRoute
  '/golden': typeof GoldenRoute
  '/login': typeof LoginRoute
  '/mis': typeof MisRoute
  '/overrides': typeof OverridesRoute
  '/policy': typeof PolicyRoute
  '/run': typeof RunRoute
  '/case/$caseId': typeof CaseCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/desk': typeof DeskRoute
  '/golden': typeof GoldenRoute
  '/login': typeof LoginRoute
  '/mis': typeof MisRoute
  '/overrides': typeof OverridesRoute
  '/policy': typeof PolicyRoute
  '/run': typeof RunRoute
  '/case/$caseId': typeof CaseCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/desk': typeof DeskRoute
  '/golden': typeof GoldenRoute
  '/login': typeof LoginRoute
  '/mis': typeof MisRoute
  '/overrides': typeof OverridesRoute
  '/policy': typeof PolicyRoute
  '/run': typeof RunRoute
  '/case/$caseId': typeof CaseCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/desk'
    | '/golden'
    | '/login'
    | '/mis'
    | '/overrides'
    | '/policy'
    | '/run'
    | '/case/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/desk'
    | '/golden'
    | '/login'
    | '/mis'
    | '/overrides'
    | '/policy'
    | '/run'
    | '/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/desk'
    | '/golden'
    | '/login'
    | '/mis'
    | '/overrides'
    | '/policy'
    | '/run'
    | '/case/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DeskRoute: typeof DeskRoute
  GoldenRoute: typeof GoldenRoute
  LoginRoute: typeof LoginRoute
  MisRoute: typeof MisRoute
  OverridesRoute: typeof OverridesRoute
  PolicyRoute: typeof PolicyRoute
  RunRoute: typeof RunRoute
  CaseCaseIdRoute: typeof CaseCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golden': {
      id: '/golden'
      path: '/golden'
      fullPath: '/golden'
      preLoaderRoute: typeof GoldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis': {
      id: '/mis'
      path: '/mis'
      fullPath: '/mis'
      preLoaderRoute: typeof MisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overrides': {
      id: '/overrides'
      path: '/overrides'
      fullPath: '/overrides'
      preLoaderRoute: typeof OverridesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DeskRoute: DeskRoute,
  GoldenRoute: GoldenRoute,
  LoginRoute: LoginRoute,
  MisRoute: MisRoute,
  OverridesRoute: OverridesRoute,
  PolicyRoute: PolicyRoute,
  RunRoute: RunRoute,
  CaseCaseIdRoute: CaseCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
